// <auto-generated />
using System;
using JavaHateBE.model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JavaHateBE.Migrations
{
    [DbContext(typeof(SampleDBContext))]
    partial class SampleDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("JavaHateBE.model.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameMode")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("JavaHateBE.model.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("Answer")
                        .HasColumnType("REAL");

                    b.Property<byte>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4147515c-17b3-4cf1-8ac4-460bfaba9a2d"),
                            Answer = 1f,
                            Difficulty = (byte)1,
                            Text = "1 + 0"
                        },
                        new
                        {
                            Id = new Guid("65152cdf-8478-479d-83da-f69c10cb671f"),
                            Answer = 2f,
                            Difficulty = (byte)1,
                            Text = "1 + 1"
                        },
                        new
                        {
                            Id = new Guid("87bb4ff0-5fdc-47ea-8f8c-671772b65c50"),
                            Answer = 3f,
                            Difficulty = (byte)1,
                            Text = "1 + 2"
                        },
                        new
                        {
                            Id = new Guid("9ba342c5-9676-4e5c-85b1-31d43555043f"),
                            Answer = 4f,
                            Difficulty = (byte)1,
                            Text = "1 + 3"
                        },
                        new
                        {
                            Id = new Guid("12a6f1ed-dd3a-4ca9-8cd8-be8f987d6f5b"),
                            Answer = 5f,
                            Difficulty = (byte)1,
                            Text = "1 + 4"
                        },
                        new
                        {
                            Id = new Guid("4329603d-4d24-4fb8-8c34-5435bf09ee92"),
                            Answer = 6f,
                            Difficulty = (byte)1,
                            Text = "1 + 5"
                        },
                        new
                        {
                            Id = new Guid("9bf4b61d-60b2-484e-9ea8-9c8f914b037a"),
                            Answer = 7f,
                            Difficulty = (byte)1,
                            Text = "1 + 6"
                        },
                        new
                        {
                            Id = new Guid("8badd258-c674-4631-a625-54348fc0a823"),
                            Answer = 8f,
                            Difficulty = (byte)1,
                            Text = "1 + 7"
                        },
                        new
                        {
                            Id = new Guid("46bea4bc-0b4e-4b14-a03f-64ee95542cbd"),
                            Answer = 9f,
                            Difficulty = (byte)1,
                            Text = "1 + 8"
                        },
                        new
                        {
                            Id = new Guid("60a1cf46-6655-4651-a2e2-ad8eb97bbf67"),
                            Answer = 10f,
                            Difficulty = (byte)1,
                            Text = "1 + 9"
                        },
                        new
                        {
                            Id = new Guid("5463343b-6603-49b4-bd5c-e72a0b18c97e"),
                            Answer = 11f,
                            Difficulty = (byte)1,
                            Text = "1 + 10"
                        },
                        new
                        {
                            Id = new Guid("da292caf-4d38-43c5-a41a-08d16909e518"),
                            Answer = 12f,
                            Difficulty = (byte)1,
                            Text = "1 + 11"
                        },
                        new
                        {
                            Id = new Guid("542c8876-7da1-4d34-b21e-2cff71136a7a"),
                            Answer = 13f,
                            Difficulty = (byte)1,
                            Text = "1 + 12"
                        },
                        new
                        {
                            Id = new Guid("8171086b-2d9f-4c1e-904f-4b6c011cd2f2"),
                            Answer = 14f,
                            Difficulty = (byte)1,
                            Text = "1 + 13"
                        },
                        new
                        {
                            Id = new Guid("141d38a3-0b5c-45b3-b3ee-637a09f390ea"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "1 + 14"
                        },
                        new
                        {
                            Id = new Guid("5de8a92e-5df0-49d9-84ec-38b7a9359c2b"),
                            Answer = 2f,
                            Difficulty = (byte)1,
                            Text = "2 + 0"
                        },
                        new
                        {
                            Id = new Guid("9c95ba14-5bef-47e8-902f-005cfa0b522a"),
                            Answer = 3f,
                            Difficulty = (byte)1,
                            Text = "2 + 1"
                        },
                        new
                        {
                            Id = new Guid("4526df6d-1c3b-49aa-a256-fc38a0392118"),
                            Answer = 4f,
                            Difficulty = (byte)1,
                            Text = "2 + 2"
                        },
                        new
                        {
                            Id = new Guid("7ef9c795-7951-404d-a80a-ffd6ab38375c"),
                            Answer = 5f,
                            Difficulty = (byte)1,
                            Text = "2 + 3"
                        },
                        new
                        {
                            Id = new Guid("6624a104-da37-46fc-8b15-09102d5ef5d0"),
                            Answer = 6f,
                            Difficulty = (byte)1,
                            Text = "2 + 4"
                        },
                        new
                        {
                            Id = new Guid("19360b01-4af3-43d7-8266-e1cc1d0719db"),
                            Answer = 7f,
                            Difficulty = (byte)1,
                            Text = "2 + 5"
                        },
                        new
                        {
                            Id = new Guid("7dbd6b2c-efdb-4a42-aafd-ccd3fd8ee422"),
                            Answer = 8f,
                            Difficulty = (byte)1,
                            Text = "2 + 6"
                        },
                        new
                        {
                            Id = new Guid("56b817eb-a313-4a04-979b-94e20b6eb327"),
                            Answer = 9f,
                            Difficulty = (byte)1,
                            Text = "2 + 7"
                        },
                        new
                        {
                            Id = new Guid("2971e466-a8b4-4d10-b39b-b8f476f5065a"),
                            Answer = 10f,
                            Difficulty = (byte)1,
                            Text = "2 + 8"
                        },
                        new
                        {
                            Id = new Guid("3d8ffb20-b4ca-4e9a-a33d-914b04e8885c"),
                            Answer = 11f,
                            Difficulty = (byte)1,
                            Text = "2 + 9"
                        },
                        new
                        {
                            Id = new Guid("d00207a8-ed91-4c87-b06b-71fa18e1240c"),
                            Answer = 12f,
                            Difficulty = (byte)1,
                            Text = "2 + 10"
                        },
                        new
                        {
                            Id = new Guid("16ecd8af-6614-4670-83a9-f12b9fa1b125"),
                            Answer = 13f,
                            Difficulty = (byte)1,
                            Text = "2 + 11"
                        },
                        new
                        {
                            Id = new Guid("9b974246-3e50-42f0-9810-1fdc277128c2"),
                            Answer = 14f,
                            Difficulty = (byte)1,
                            Text = "2 + 12"
                        },
                        new
                        {
                            Id = new Guid("9bcfcef0-eafb-4750-a6ea-0b39648691e9"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "2 + 13"
                        },
                        new
                        {
                            Id = new Guid("7386391a-c781-4529-afe1-a16e4d0e77fd"),
                            Answer = 16f,
                            Difficulty = (byte)1,
                            Text = "2 + 14"
                        },
                        new
                        {
                            Id = new Guid("96cbf69a-2975-496b-9b6e-43c03f913063"),
                            Answer = 3f,
                            Difficulty = (byte)1,
                            Text = "3 + 0"
                        },
                        new
                        {
                            Id = new Guid("5f937cb5-8579-40ed-9b86-4e48fd4b328f"),
                            Answer = 4f,
                            Difficulty = (byte)1,
                            Text = "3 + 1"
                        },
                        new
                        {
                            Id = new Guid("55c46172-59ba-4557-9f5c-1dbe691c840d"),
                            Answer = 5f,
                            Difficulty = (byte)1,
                            Text = "3 + 2"
                        },
                        new
                        {
                            Id = new Guid("ab23c0b9-c819-4ad1-8fea-5be5eaaea418"),
                            Answer = 6f,
                            Difficulty = (byte)1,
                            Text = "3 + 3"
                        },
                        new
                        {
                            Id = new Guid("df3ad41e-49bd-4fd6-8706-19ac46169a4f"),
                            Answer = 7f,
                            Difficulty = (byte)1,
                            Text = "3 + 4"
                        },
                        new
                        {
                            Id = new Guid("fe624533-073a-46a0-aa69-0faade3425cc"),
                            Answer = 8f,
                            Difficulty = (byte)1,
                            Text = "3 + 5"
                        },
                        new
                        {
                            Id = new Guid("e95403e0-a21e-4eb6-a0e8-c0f998abce77"),
                            Answer = 9f,
                            Difficulty = (byte)1,
                            Text = "3 + 6"
                        },
                        new
                        {
                            Id = new Guid("f3d17e55-5e27-4bd2-8b3a-7e027a965c64"),
                            Answer = 10f,
                            Difficulty = (byte)1,
                            Text = "3 + 7"
                        },
                        new
                        {
                            Id = new Guid("56cbb2be-860d-44ff-9c30-00ef22c1392c"),
                            Answer = 11f,
                            Difficulty = (byte)1,
                            Text = "3 + 8"
                        },
                        new
                        {
                            Id = new Guid("e4990ad6-6e7e-4d49-958b-24b8a618ad07"),
                            Answer = 12f,
                            Difficulty = (byte)1,
                            Text = "3 + 9"
                        },
                        new
                        {
                            Id = new Guid("1c049424-a4e6-49bf-a3d1-016851362563"),
                            Answer = 13f,
                            Difficulty = (byte)1,
                            Text = "3 + 10"
                        },
                        new
                        {
                            Id = new Guid("5c69161e-a1dd-45a7-bd1b-b1cc6dbe6e25"),
                            Answer = 14f,
                            Difficulty = (byte)1,
                            Text = "3 + 11"
                        },
                        new
                        {
                            Id = new Guid("9c314b50-b8bc-48bd-a41b-46fde4df577f"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "3 + 12"
                        },
                        new
                        {
                            Id = new Guid("647e468b-33fd-429b-8992-b078ca505e75"),
                            Answer = 16f,
                            Difficulty = (byte)1,
                            Text = "3 + 13"
                        },
                        new
                        {
                            Id = new Guid("330b197e-0f20-44e1-941e-4734e963c018"),
                            Answer = 17f,
                            Difficulty = (byte)1,
                            Text = "3 + 14"
                        },
                        new
                        {
                            Id = new Guid("e664c3dc-ec4e-40ea-b901-a613f76a8116"),
                            Answer = 4f,
                            Difficulty = (byte)1,
                            Text = "4 + 0"
                        },
                        new
                        {
                            Id = new Guid("a220449e-d251-448e-9c6a-5f32c53c8b11"),
                            Answer = 5f,
                            Difficulty = (byte)1,
                            Text = "4 + 1"
                        },
                        new
                        {
                            Id = new Guid("88d3811e-b19a-4d98-a2c9-0d5c78a76c53"),
                            Answer = 6f,
                            Difficulty = (byte)1,
                            Text = "4 + 2"
                        },
                        new
                        {
                            Id = new Guid("4f6511b9-f11b-4ffd-a413-5196f2ba151c"),
                            Answer = 7f,
                            Difficulty = (byte)1,
                            Text = "4 + 3"
                        },
                        new
                        {
                            Id = new Guid("c1bda796-ce9e-4ec2-8ba0-c9a8c8436ddf"),
                            Answer = 8f,
                            Difficulty = (byte)1,
                            Text = "4 + 4"
                        },
                        new
                        {
                            Id = new Guid("dc284571-7d0d-4ac0-8b86-3d496369191f"),
                            Answer = 9f,
                            Difficulty = (byte)1,
                            Text = "4 + 5"
                        },
                        new
                        {
                            Id = new Guid("3561c725-46fa-433e-9176-1a5543da915b"),
                            Answer = 10f,
                            Difficulty = (byte)1,
                            Text = "4 + 6"
                        },
                        new
                        {
                            Id = new Guid("18644b19-5bfa-40b5-9394-6984c9c4da1a"),
                            Answer = 11f,
                            Difficulty = (byte)1,
                            Text = "4 + 7"
                        },
                        new
                        {
                            Id = new Guid("cae63f60-e489-42b7-8d15-3afad69e20b5"),
                            Answer = 12f,
                            Difficulty = (byte)1,
                            Text = "4 + 8"
                        },
                        new
                        {
                            Id = new Guid("9c1fdcd3-a43d-4407-99f2-23eac74af576"),
                            Answer = 13f,
                            Difficulty = (byte)1,
                            Text = "4 + 9"
                        },
                        new
                        {
                            Id = new Guid("3139cfe5-ca6f-4c16-ab08-777e69be00a3"),
                            Answer = 14f,
                            Difficulty = (byte)1,
                            Text = "4 + 10"
                        },
                        new
                        {
                            Id = new Guid("ad56f05b-8c69-4450-bba5-b888ec15f638"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "4 + 11"
                        },
                        new
                        {
                            Id = new Guid("144cad9e-a2da-48bf-8146-af65c641f44a"),
                            Answer = 16f,
                            Difficulty = (byte)1,
                            Text = "4 + 12"
                        },
                        new
                        {
                            Id = new Guid("c3651a3e-f9a8-4d0a-8342-da0b601c9df1"),
                            Answer = 17f,
                            Difficulty = (byte)1,
                            Text = "4 + 13"
                        },
                        new
                        {
                            Id = new Guid("0315ad97-3215-4ba6-b7d2-4fa501dd7942"),
                            Answer = 18f,
                            Difficulty = (byte)1,
                            Text = "4 + 14"
                        },
                        new
                        {
                            Id = new Guid("1dfae402-8866-46cb-895d-ba48555947fa"),
                            Answer = 5f,
                            Difficulty = (byte)1,
                            Text = "5 + 0"
                        },
                        new
                        {
                            Id = new Guid("2079f50e-508e-4e5b-85b3-42cb1cb30a92"),
                            Answer = 6f,
                            Difficulty = (byte)1,
                            Text = "5 + 1"
                        },
                        new
                        {
                            Id = new Guid("e970b918-7a09-4398-a95e-d810a9804218"),
                            Answer = 7f,
                            Difficulty = (byte)1,
                            Text = "5 + 2"
                        },
                        new
                        {
                            Id = new Guid("68a9ca64-5771-4d74-81a5-b0023dadbb69"),
                            Answer = 8f,
                            Difficulty = (byte)1,
                            Text = "5 + 3"
                        },
                        new
                        {
                            Id = new Guid("ec420d16-3e1c-4ea1-9cdb-7c2b3df700b8"),
                            Answer = 9f,
                            Difficulty = (byte)1,
                            Text = "5 + 4"
                        },
                        new
                        {
                            Id = new Guid("99027f1e-827a-4394-bdd1-8f0b5d4a3d7b"),
                            Answer = 10f,
                            Difficulty = (byte)1,
                            Text = "5 + 5"
                        },
                        new
                        {
                            Id = new Guid("7e6a2bd9-2a2e-4b7f-8182-92a73b376117"),
                            Answer = 11f,
                            Difficulty = (byte)1,
                            Text = "5 + 6"
                        },
                        new
                        {
                            Id = new Guid("61f3a9a8-ca6b-443a-926f-2f8e0a625066"),
                            Answer = 12f,
                            Difficulty = (byte)1,
                            Text = "5 + 7"
                        },
                        new
                        {
                            Id = new Guid("4bf124b5-61e1-4b9a-a58c-ae466ae8c032"),
                            Answer = 13f,
                            Difficulty = (byte)1,
                            Text = "5 + 8"
                        },
                        new
                        {
                            Id = new Guid("ce77cdb1-f224-4cbc-965d-c29dd7772630"),
                            Answer = 14f,
                            Difficulty = (byte)1,
                            Text = "5 + 9"
                        },
                        new
                        {
                            Id = new Guid("613d8bf6-9080-4527-948c-7973dad63f70"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "5 + 10"
                        },
                        new
                        {
                            Id = new Guid("3931fec2-addb-41cb-bc70-7f0dc11d971b"),
                            Answer = 16f,
                            Difficulty = (byte)1,
                            Text = "5 + 11"
                        },
                        new
                        {
                            Id = new Guid("f72428df-7526-46ff-b51d-f101d5e86317"),
                            Answer = 17f,
                            Difficulty = (byte)1,
                            Text = "5 + 12"
                        },
                        new
                        {
                            Id = new Guid("d48aeddf-5090-40a9-ac6a-d3fa668b618f"),
                            Answer = 18f,
                            Difficulty = (byte)1,
                            Text = "5 + 13"
                        },
                        new
                        {
                            Id = new Guid("9ae9b551-4a98-467b-932a-1c023cefa487"),
                            Answer = 19f,
                            Difficulty = (byte)1,
                            Text = "5 + 14"
                        },
                        new
                        {
                            Id = new Guid("29ec8618-9310-4ddd-a63c-baad5006e814"),
                            Answer = 6f,
                            Difficulty = (byte)1,
                            Text = "6 + 0"
                        },
                        new
                        {
                            Id = new Guid("e245e2fd-e1c9-4277-9129-dc0b3649f75c"),
                            Answer = 7f,
                            Difficulty = (byte)1,
                            Text = "6 + 1"
                        },
                        new
                        {
                            Id = new Guid("8c894268-876d-4248-b5e8-4cb5e9c1be51"),
                            Answer = 8f,
                            Difficulty = (byte)1,
                            Text = "6 + 2"
                        },
                        new
                        {
                            Id = new Guid("facbc299-f4ef-48a8-a79b-5dbdce3aa5d7"),
                            Answer = 9f,
                            Difficulty = (byte)1,
                            Text = "6 + 3"
                        },
                        new
                        {
                            Id = new Guid("e2b44890-b25c-4b38-b42a-49472dc97db0"),
                            Answer = 10f,
                            Difficulty = (byte)1,
                            Text = "6 + 4"
                        },
                        new
                        {
                            Id = new Guid("a97f2827-5f0d-4684-8ecb-101bed93615d"),
                            Answer = 11f,
                            Difficulty = (byte)1,
                            Text = "6 + 5"
                        },
                        new
                        {
                            Id = new Guid("705c8d9d-c05e-414b-a2ae-af742d722f70"),
                            Answer = 12f,
                            Difficulty = (byte)1,
                            Text = "6 + 6"
                        },
                        new
                        {
                            Id = new Guid("dd71ca68-e47b-423a-ad4b-ed15d3555ee8"),
                            Answer = 13f,
                            Difficulty = (byte)1,
                            Text = "6 + 7"
                        },
                        new
                        {
                            Id = new Guid("b3ce327a-94bf-4fd8-9f4d-560a0102683a"),
                            Answer = 14f,
                            Difficulty = (byte)1,
                            Text = "6 + 8"
                        },
                        new
                        {
                            Id = new Guid("aff138e8-abfe-4844-8ab5-1ba43d82f25d"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "6 + 9"
                        },
                        new
                        {
                            Id = new Guid("7e1bef1f-0b38-4e4f-b4f6-02e51ef09d40"),
                            Answer = 16f,
                            Difficulty = (byte)1,
                            Text = "6 + 10"
                        },
                        new
                        {
                            Id = new Guid("20e06049-ac11-4707-8479-453a1e68258e"),
                            Answer = 17f,
                            Difficulty = (byte)1,
                            Text = "6 + 11"
                        },
                        new
                        {
                            Id = new Guid("6af36c9a-bfc0-4f47-95e9-f8f7af775c18"),
                            Answer = 18f,
                            Difficulty = (byte)1,
                            Text = "6 + 12"
                        },
                        new
                        {
                            Id = new Guid("c7f6b861-0fd4-438c-94a9-55693f08afb9"),
                            Answer = 19f,
                            Difficulty = (byte)1,
                            Text = "6 + 13"
                        },
                        new
                        {
                            Id = new Guid("c7ee4cf2-4ca2-4e27-bb60-22736143d5e1"),
                            Answer = 20f,
                            Difficulty = (byte)1,
                            Text = "6 + 14"
                        },
                        new
                        {
                            Id = new Guid("8d64d4e2-4ec9-4e06-878e-387e31e49474"),
                            Answer = 7f,
                            Difficulty = (byte)1,
                            Text = "7 + 0"
                        },
                        new
                        {
                            Id = new Guid("e3999c72-d1ca-4421-89d9-29e4bfcb7e8a"),
                            Answer = 8f,
                            Difficulty = (byte)1,
                            Text = "7 + 1"
                        },
                        new
                        {
                            Id = new Guid("a6f3d295-e64a-4968-9145-aa14b7e44adc"),
                            Answer = 9f,
                            Difficulty = (byte)1,
                            Text = "7 + 2"
                        },
                        new
                        {
                            Id = new Guid("5193775c-8303-49d9-8e0a-158470773178"),
                            Answer = 10f,
                            Difficulty = (byte)1,
                            Text = "7 + 3"
                        },
                        new
                        {
                            Id = new Guid("a2dfdca1-4b5b-4a9d-8654-dd21e1930c49"),
                            Answer = 11f,
                            Difficulty = (byte)1,
                            Text = "7 + 4"
                        },
                        new
                        {
                            Id = new Guid("47bbae4c-76d8-4283-973a-b3e63e78cfb4"),
                            Answer = 12f,
                            Difficulty = (byte)1,
                            Text = "7 + 5"
                        },
                        new
                        {
                            Id = new Guid("abb89eac-3c1d-4230-a124-1b1615c0b6c0"),
                            Answer = 13f,
                            Difficulty = (byte)1,
                            Text = "7 + 6"
                        },
                        new
                        {
                            Id = new Guid("2be501a3-9269-410c-94c3-9bf95ec993dd"),
                            Answer = 14f,
                            Difficulty = (byte)1,
                            Text = "7 + 7"
                        },
                        new
                        {
                            Id = new Guid("7e8fbd28-8eba-4cee-973d-dce2701581fd"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "7 + 8"
                        },
                        new
                        {
                            Id = new Guid("f0374d96-e9e3-4802-9495-018281e7da8f"),
                            Answer = 16f,
                            Difficulty = (byte)1,
                            Text = "7 + 9"
                        },
                        new
                        {
                            Id = new Guid("803ccbe4-4b1d-4416-ab60-c1b2c4898e7a"),
                            Answer = 17f,
                            Difficulty = (byte)1,
                            Text = "7 + 10"
                        },
                        new
                        {
                            Id = new Guid("29934a15-2c0e-488b-8920-59c799fbfbb3"),
                            Answer = 18f,
                            Difficulty = (byte)1,
                            Text = "7 + 11"
                        },
                        new
                        {
                            Id = new Guid("d415f04a-1c35-44f3-b7d1-f5800c8ac963"),
                            Answer = 19f,
                            Difficulty = (byte)1,
                            Text = "7 + 12"
                        },
                        new
                        {
                            Id = new Guid("fd952aa2-b8d9-4e17-814e-4e8f85e16a92"),
                            Answer = 20f,
                            Difficulty = (byte)1,
                            Text = "7 + 13"
                        },
                        new
                        {
                            Id = new Guid("7bf048a3-bf01-4520-9514-ab1ab90bf787"),
                            Answer = 21f,
                            Difficulty = (byte)1,
                            Text = "7 + 14"
                        },
                        new
                        {
                            Id = new Guid("45f7abd1-6ac1-4e83-b198-8981a6dab6a4"),
                            Answer = 8f,
                            Difficulty = (byte)1,
                            Text = "8 + 0"
                        },
                        new
                        {
                            Id = new Guid("4aebc357-861e-45b1-95cb-6988ca0f6fe5"),
                            Answer = 9f,
                            Difficulty = (byte)1,
                            Text = "8 + 1"
                        },
                        new
                        {
                            Id = new Guid("5d888602-c7c8-4aed-9930-65b5138970cb"),
                            Answer = 10f,
                            Difficulty = (byte)1,
                            Text = "8 + 2"
                        },
                        new
                        {
                            Id = new Guid("5906595d-d9c5-43a2-ae81-ba9b4affa88e"),
                            Answer = 11f,
                            Difficulty = (byte)1,
                            Text = "8 + 3"
                        },
                        new
                        {
                            Id = new Guid("549b5ecf-09cf-46eb-9a7f-df5c8a49176c"),
                            Answer = 12f,
                            Difficulty = (byte)1,
                            Text = "8 + 4"
                        },
                        new
                        {
                            Id = new Guid("cbd424a5-0484-4911-ae1c-b41c3e2b8d79"),
                            Answer = 13f,
                            Difficulty = (byte)1,
                            Text = "8 + 5"
                        },
                        new
                        {
                            Id = new Guid("1278e732-65b1-4782-bc3d-d4d73c4c013f"),
                            Answer = 14f,
                            Difficulty = (byte)1,
                            Text = "8 + 6"
                        },
                        new
                        {
                            Id = new Guid("6122a062-a434-48f9-8e55-32914df78221"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "8 + 7"
                        },
                        new
                        {
                            Id = new Guid("b54aa4b8-1fce-4a99-92e0-b1ba412d7c6d"),
                            Answer = 16f,
                            Difficulty = (byte)1,
                            Text = "8 + 8"
                        },
                        new
                        {
                            Id = new Guid("932582af-c651-4d77-b730-f7e14fb6a798"),
                            Answer = 17f,
                            Difficulty = (byte)1,
                            Text = "8 + 9"
                        },
                        new
                        {
                            Id = new Guid("eabc115a-658d-4775-bcae-8c251df04616"),
                            Answer = 18f,
                            Difficulty = (byte)1,
                            Text = "8 + 10"
                        },
                        new
                        {
                            Id = new Guid("5e41039a-5e5d-41f6-91eb-e93a3100f74d"),
                            Answer = 19f,
                            Difficulty = (byte)1,
                            Text = "8 + 11"
                        },
                        new
                        {
                            Id = new Guid("c700ceb3-7bfd-488c-87f1-a96a4cc95b8d"),
                            Answer = 20f,
                            Difficulty = (byte)1,
                            Text = "8 + 12"
                        },
                        new
                        {
                            Id = new Guid("f62c2946-1892-40ba-bc7e-3f50ec19efdb"),
                            Answer = 21f,
                            Difficulty = (byte)1,
                            Text = "8 + 13"
                        },
                        new
                        {
                            Id = new Guid("9849a143-ca26-4366-b443-a43360ad7351"),
                            Answer = 22f,
                            Difficulty = (byte)1,
                            Text = "8 + 14"
                        },
                        new
                        {
                            Id = new Guid("458b732c-9362-42ed-b781-764a425df2cc"),
                            Answer = 9f,
                            Difficulty = (byte)1,
                            Text = "9 + 0"
                        },
                        new
                        {
                            Id = new Guid("cf36f11d-b7cc-4045-bfb4-caa7ecbddaf6"),
                            Answer = 10f,
                            Difficulty = (byte)1,
                            Text = "9 + 1"
                        },
                        new
                        {
                            Id = new Guid("8d616bd5-a704-43dd-8d41-3016474f2a18"),
                            Answer = 11f,
                            Difficulty = (byte)1,
                            Text = "9 + 2"
                        },
                        new
                        {
                            Id = new Guid("c00f9aeb-13d1-4766-a3ce-d6c8b4464343"),
                            Answer = 12f,
                            Difficulty = (byte)1,
                            Text = "9 + 3"
                        },
                        new
                        {
                            Id = new Guid("b5c7a790-0b85-4318-9482-981df9db017f"),
                            Answer = 13f,
                            Difficulty = (byte)1,
                            Text = "9 + 4"
                        },
                        new
                        {
                            Id = new Guid("3bca1897-3ba4-463d-a520-99b69983d1e2"),
                            Answer = 14f,
                            Difficulty = (byte)1,
                            Text = "9 + 5"
                        },
                        new
                        {
                            Id = new Guid("b210facb-a5da-4c3e-8e77-9ca187994747"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "9 + 6"
                        },
                        new
                        {
                            Id = new Guid("41d04a71-8241-4fe6-a93a-92a53f674dee"),
                            Answer = 16f,
                            Difficulty = (byte)1,
                            Text = "9 + 7"
                        },
                        new
                        {
                            Id = new Guid("9f6e091a-1762-4f7a-a69e-fadfe6012ebf"),
                            Answer = 17f,
                            Difficulty = (byte)1,
                            Text = "9 + 8"
                        },
                        new
                        {
                            Id = new Guid("875810aa-0d2f-4d82-9bd6-834937f775b3"),
                            Answer = 18f,
                            Difficulty = (byte)1,
                            Text = "9 + 9"
                        },
                        new
                        {
                            Id = new Guid("c1262a3f-18f3-441b-88ba-39b28cf02edc"),
                            Answer = 19f,
                            Difficulty = (byte)1,
                            Text = "9 + 10"
                        },
                        new
                        {
                            Id = new Guid("5222e0b5-653f-4da8-8b80-821661460dd6"),
                            Answer = 20f,
                            Difficulty = (byte)1,
                            Text = "9 + 11"
                        },
                        new
                        {
                            Id = new Guid("ec1b152f-2ba3-463d-ae22-335e219332d9"),
                            Answer = 21f,
                            Difficulty = (byte)1,
                            Text = "9 + 12"
                        },
                        new
                        {
                            Id = new Guid("dc141469-f899-4930-a669-d443160e0ceb"),
                            Answer = 22f,
                            Difficulty = (byte)1,
                            Text = "9 + 13"
                        },
                        new
                        {
                            Id = new Guid("dca5c3ef-f834-4f97-86c1-22e2e12a0ad1"),
                            Answer = 23f,
                            Difficulty = (byte)1,
                            Text = "9 + 14"
                        },
                        new
                        {
                            Id = new Guid("ecfb091c-fc5f-450f-8544-f6923412c3b3"),
                            Answer = 10f,
                            Difficulty = (byte)1,
                            Text = "10 + 0"
                        },
                        new
                        {
                            Id = new Guid("39427a49-4bfc-4fe0-ac55-a00ef8ccff39"),
                            Answer = 11f,
                            Difficulty = (byte)1,
                            Text = "10 + 1"
                        },
                        new
                        {
                            Id = new Guid("b0c83071-3bde-4cb1-bbdf-c37448c804b0"),
                            Answer = 12f,
                            Difficulty = (byte)1,
                            Text = "10 + 2"
                        },
                        new
                        {
                            Id = new Guid("9032b542-af56-4294-b275-6a8185dace4b"),
                            Answer = 13f,
                            Difficulty = (byte)1,
                            Text = "10 + 3"
                        },
                        new
                        {
                            Id = new Guid("d3466c23-a754-4e32-8b94-97a3cfd64228"),
                            Answer = 14f,
                            Difficulty = (byte)1,
                            Text = "10 + 4"
                        },
                        new
                        {
                            Id = new Guid("858bfa14-73de-4238-b4e8-1461fc174d5e"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "10 + 5"
                        },
                        new
                        {
                            Id = new Guid("0fb0deae-6973-40a0-8e14-f681ab287da2"),
                            Answer = 16f,
                            Difficulty = (byte)1,
                            Text = "10 + 6"
                        },
                        new
                        {
                            Id = new Guid("cd21b27d-0bdf-4fd2-a505-ab7985780185"),
                            Answer = 17f,
                            Difficulty = (byte)1,
                            Text = "10 + 7"
                        },
                        new
                        {
                            Id = new Guid("a000ba43-49bc-432b-b562-3b8010cabd89"),
                            Answer = 18f,
                            Difficulty = (byte)1,
                            Text = "10 + 8"
                        },
                        new
                        {
                            Id = new Guid("b647f8e5-623d-4db7-aea6-3c366c3da6e8"),
                            Answer = 19f,
                            Difficulty = (byte)1,
                            Text = "10 + 9"
                        },
                        new
                        {
                            Id = new Guid("8c172e64-be00-4641-9836-a5c9e6e88843"),
                            Answer = 20f,
                            Difficulty = (byte)1,
                            Text = "10 + 10"
                        },
                        new
                        {
                            Id = new Guid("46ad150c-df25-46d6-ba20-416d7f6ca560"),
                            Answer = 21f,
                            Difficulty = (byte)1,
                            Text = "10 + 11"
                        },
                        new
                        {
                            Id = new Guid("8a34f6ba-408c-4ca2-8424-c53e1638f83b"),
                            Answer = 22f,
                            Difficulty = (byte)1,
                            Text = "10 + 12"
                        },
                        new
                        {
                            Id = new Guid("a2452253-006c-4ccb-848c-0200bc40278e"),
                            Answer = 23f,
                            Difficulty = (byte)1,
                            Text = "10 + 13"
                        },
                        new
                        {
                            Id = new Guid("e7ab120c-a8bc-42ad-afce-ba8fee3454b5"),
                            Answer = 24f,
                            Difficulty = (byte)1,
                            Text = "10 + 14"
                        },
                        new
                        {
                            Id = new Guid("011bbaeb-5b64-4ac4-a10f-06f3c0aaa877"),
                            Answer = 11f,
                            Difficulty = (byte)1,
                            Text = "11 + 0"
                        },
                        new
                        {
                            Id = new Guid("de185fc8-4795-4d33-93c7-1da4db669975"),
                            Answer = 12f,
                            Difficulty = (byte)1,
                            Text = "11 + 1"
                        },
                        new
                        {
                            Id = new Guid("6f40497b-393d-486e-9adc-623940c92f6f"),
                            Answer = 13f,
                            Difficulty = (byte)1,
                            Text = "11 + 2"
                        },
                        new
                        {
                            Id = new Guid("5faa314a-6b76-4dcc-9acb-e39deace7b70"),
                            Answer = 14f,
                            Difficulty = (byte)1,
                            Text = "11 + 3"
                        },
                        new
                        {
                            Id = new Guid("8e984bbe-ac39-4969-a753-76009c1fb4af"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "11 + 4"
                        },
                        new
                        {
                            Id = new Guid("1c59b022-fc6b-4551-9b0d-cc4e180ef986"),
                            Answer = 16f,
                            Difficulty = (byte)1,
                            Text = "11 + 5"
                        },
                        new
                        {
                            Id = new Guid("e5bc9f1b-31ce-443a-aa67-348ab93bdae0"),
                            Answer = 17f,
                            Difficulty = (byte)1,
                            Text = "11 + 6"
                        },
                        new
                        {
                            Id = new Guid("ad214681-226d-404e-8638-72c239566104"),
                            Answer = 18f,
                            Difficulty = (byte)1,
                            Text = "11 + 7"
                        },
                        new
                        {
                            Id = new Guid("154c24c1-5ac7-43f7-a638-d7e02e60ae0c"),
                            Answer = 19f,
                            Difficulty = (byte)1,
                            Text = "11 + 8"
                        },
                        new
                        {
                            Id = new Guid("20df3a02-3a72-45e7-b4ac-58727daef0cf"),
                            Answer = 20f,
                            Difficulty = (byte)1,
                            Text = "11 + 9"
                        },
                        new
                        {
                            Id = new Guid("1ef5f07a-1392-478a-bcad-cf9fcc010118"),
                            Answer = 21f,
                            Difficulty = (byte)1,
                            Text = "11 + 10"
                        },
                        new
                        {
                            Id = new Guid("67338c1c-029b-4131-9432-62d41488e16b"),
                            Answer = 22f,
                            Difficulty = (byte)1,
                            Text = "11 + 11"
                        },
                        new
                        {
                            Id = new Guid("e349feca-ca6d-41e1-ad85-68ee3ad22591"),
                            Answer = 23f,
                            Difficulty = (byte)1,
                            Text = "11 + 12"
                        },
                        new
                        {
                            Id = new Guid("8df802b3-6c55-4c12-bfb5-1f66eaa7f30e"),
                            Answer = 24f,
                            Difficulty = (byte)1,
                            Text = "11 + 13"
                        },
                        new
                        {
                            Id = new Guid("c19cbd73-511f-4fea-bad7-58f92957ab95"),
                            Answer = 25f,
                            Difficulty = (byte)1,
                            Text = "11 + 14"
                        },
                        new
                        {
                            Id = new Guid("f1ffcfcb-0aa8-4301-a9b5-0501421c7bab"),
                            Answer = 12f,
                            Difficulty = (byte)1,
                            Text = "12 + 0"
                        },
                        new
                        {
                            Id = new Guid("2f73753e-5eea-4f7b-a0ae-2243bf696823"),
                            Answer = 13f,
                            Difficulty = (byte)1,
                            Text = "12 + 1"
                        },
                        new
                        {
                            Id = new Guid("a1ad4adf-b9fe-451b-b171-23ab31c5731d"),
                            Answer = 14f,
                            Difficulty = (byte)1,
                            Text = "12 + 2"
                        },
                        new
                        {
                            Id = new Guid("d756dfdf-90b0-4c4a-8ef8-d8692e8c4891"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "12 + 3"
                        },
                        new
                        {
                            Id = new Guid("52ecc2a6-7183-4aa6-bfa3-e28010d4c7c6"),
                            Answer = 16f,
                            Difficulty = (byte)1,
                            Text = "12 + 4"
                        },
                        new
                        {
                            Id = new Guid("4482d0dc-8b35-40d5-8550-bde8f40733ed"),
                            Answer = 17f,
                            Difficulty = (byte)1,
                            Text = "12 + 5"
                        },
                        new
                        {
                            Id = new Guid("3081bd52-2094-4fa9-9eb0-571d3ff1d375"),
                            Answer = 18f,
                            Difficulty = (byte)1,
                            Text = "12 + 6"
                        },
                        new
                        {
                            Id = new Guid("4b5b8930-ede0-4dbc-94c9-ddcf7e799987"),
                            Answer = 19f,
                            Difficulty = (byte)1,
                            Text = "12 + 7"
                        },
                        new
                        {
                            Id = new Guid("8ddcc778-83cc-4d22-9fb1-8298659f21c6"),
                            Answer = 20f,
                            Difficulty = (byte)1,
                            Text = "12 + 8"
                        },
                        new
                        {
                            Id = new Guid("cbd3d830-9bc9-4f2a-937d-4b0bfa9154a3"),
                            Answer = 21f,
                            Difficulty = (byte)1,
                            Text = "12 + 9"
                        },
                        new
                        {
                            Id = new Guid("2f35c43a-f4ec-4ac7-9e9e-16b70518825b"),
                            Answer = 22f,
                            Difficulty = (byte)1,
                            Text = "12 + 10"
                        },
                        new
                        {
                            Id = new Guid("a7373afc-4041-4d40-8a92-0fe636ad7125"),
                            Answer = 23f,
                            Difficulty = (byte)1,
                            Text = "12 + 11"
                        },
                        new
                        {
                            Id = new Guid("70c89ed5-f0ff-4aea-9d29-761cab29bb88"),
                            Answer = 24f,
                            Difficulty = (byte)1,
                            Text = "12 + 12"
                        },
                        new
                        {
                            Id = new Guid("23c2db07-b421-4c82-8d8d-70d463658215"),
                            Answer = 25f,
                            Difficulty = (byte)1,
                            Text = "12 + 13"
                        },
                        new
                        {
                            Id = new Guid("cb73eb84-47d7-422e-bcf0-7b2b1f364183"),
                            Answer = 26f,
                            Difficulty = (byte)1,
                            Text = "12 + 14"
                        },
                        new
                        {
                            Id = new Guid("56b8744c-45ac-471c-8ada-b2d1d18521f6"),
                            Answer = 13f,
                            Difficulty = (byte)1,
                            Text = "13 + 0"
                        },
                        new
                        {
                            Id = new Guid("e511368c-5109-4fa8-acfe-6bd287672510"),
                            Answer = 14f,
                            Difficulty = (byte)1,
                            Text = "13 + 1"
                        },
                        new
                        {
                            Id = new Guid("75a895f9-a65f-41e0-9fd3-b14535804f1d"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "13 + 2"
                        },
                        new
                        {
                            Id = new Guid("0985d3c7-d227-4bbf-ad11-845ff6840530"),
                            Answer = 16f,
                            Difficulty = (byte)1,
                            Text = "13 + 3"
                        },
                        new
                        {
                            Id = new Guid("ff3fabb2-c3b4-4b41-8c94-102c82b15ea7"),
                            Answer = 17f,
                            Difficulty = (byte)1,
                            Text = "13 + 4"
                        },
                        new
                        {
                            Id = new Guid("60302a2e-53b3-45ee-8937-d15f4426d160"),
                            Answer = 18f,
                            Difficulty = (byte)1,
                            Text = "13 + 5"
                        },
                        new
                        {
                            Id = new Guid("0830dc1e-e47b-485f-a6ea-acc245827dd7"),
                            Answer = 19f,
                            Difficulty = (byte)1,
                            Text = "13 + 6"
                        },
                        new
                        {
                            Id = new Guid("59a14c83-8deb-44bf-b91c-f5c80227924f"),
                            Answer = 20f,
                            Difficulty = (byte)1,
                            Text = "13 + 7"
                        },
                        new
                        {
                            Id = new Guid("a6f1d5a8-2938-423c-b7ca-781c990012c4"),
                            Answer = 21f,
                            Difficulty = (byte)1,
                            Text = "13 + 8"
                        },
                        new
                        {
                            Id = new Guid("45ff3123-3bbf-4563-881b-40d9b2e85819"),
                            Answer = 22f,
                            Difficulty = (byte)1,
                            Text = "13 + 9"
                        },
                        new
                        {
                            Id = new Guid("71426c32-92a9-4458-8abf-ef99d5b6db16"),
                            Answer = 23f,
                            Difficulty = (byte)1,
                            Text = "13 + 10"
                        },
                        new
                        {
                            Id = new Guid("136b9622-3c1e-49f1-b7ff-751dca58263b"),
                            Answer = 24f,
                            Difficulty = (byte)1,
                            Text = "13 + 11"
                        },
                        new
                        {
                            Id = new Guid("26a36816-077b-467b-98b4-3a552ec545e8"),
                            Answer = 25f,
                            Difficulty = (byte)1,
                            Text = "13 + 12"
                        },
                        new
                        {
                            Id = new Guid("821eecbd-6b9b-4f0e-a081-0dd4bb8c84b4"),
                            Answer = 26f,
                            Difficulty = (byte)1,
                            Text = "13 + 13"
                        },
                        new
                        {
                            Id = new Guid("b596b0a4-a706-4ca6-ab34-9e793d898f86"),
                            Answer = 27f,
                            Difficulty = (byte)1,
                            Text = "13 + 14"
                        },
                        new
                        {
                            Id = new Guid("5cb1ad6a-1e18-4786-8b14-e2a2e4ad791c"),
                            Answer = 14f,
                            Difficulty = (byte)1,
                            Text = "14 + 0"
                        },
                        new
                        {
                            Id = new Guid("cb6eb4f7-e044-43b0-9d4c-376f573c62e1"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "14 + 1"
                        },
                        new
                        {
                            Id = new Guid("c795619e-8ac6-4744-b7fa-2ed1dfb4cbbe"),
                            Answer = 16f,
                            Difficulty = (byte)1,
                            Text = "14 + 2"
                        },
                        new
                        {
                            Id = new Guid("877397dc-edc3-4dc9-a5e4-fd8161f4d40f"),
                            Answer = 17f,
                            Difficulty = (byte)1,
                            Text = "14 + 3"
                        },
                        new
                        {
                            Id = new Guid("abf3c8ad-70cb-48a5-9a55-b35d7e2da12a"),
                            Answer = 18f,
                            Difficulty = (byte)1,
                            Text = "14 + 4"
                        },
                        new
                        {
                            Id = new Guid("52e1be02-4de9-4d2e-b884-cb0ae54cdc42"),
                            Answer = 19f,
                            Difficulty = (byte)1,
                            Text = "14 + 5"
                        },
                        new
                        {
                            Id = new Guid("2e3950fc-ef00-47c7-b663-44609b740056"),
                            Answer = 20f,
                            Difficulty = (byte)1,
                            Text = "14 + 6"
                        },
                        new
                        {
                            Id = new Guid("3cb2ea57-5510-46f6-8d01-a926d4fecca8"),
                            Answer = 21f,
                            Difficulty = (byte)1,
                            Text = "14 + 7"
                        },
                        new
                        {
                            Id = new Guid("65652316-515d-4f62-adc3-68cab828d9ca"),
                            Answer = 22f,
                            Difficulty = (byte)1,
                            Text = "14 + 8"
                        },
                        new
                        {
                            Id = new Guid("90c0b619-e562-46bf-bad9-55d1981e282c"),
                            Answer = 23f,
                            Difficulty = (byte)1,
                            Text = "14 + 9"
                        },
                        new
                        {
                            Id = new Guid("50e693d3-9236-44b0-92fa-efb0465148ec"),
                            Answer = 24f,
                            Difficulty = (byte)1,
                            Text = "14 + 10"
                        },
                        new
                        {
                            Id = new Guid("217482c6-8bc9-48d5-af0c-e416e05ed838"),
                            Answer = 25f,
                            Difficulty = (byte)1,
                            Text = "14 + 11"
                        },
                        new
                        {
                            Id = new Guid("e26b0747-0aac-4995-83af-bbfc43dccfdd"),
                            Answer = 26f,
                            Difficulty = (byte)1,
                            Text = "14 + 12"
                        },
                        new
                        {
                            Id = new Guid("626de15a-339b-41c3-a4da-93eee12941e2"),
                            Answer = 27f,
                            Difficulty = (byte)1,
                            Text = "14 + 13"
                        },
                        new
                        {
                            Id = new Guid("11cb8584-5291-4bfb-8d48-008e12c2331b"),
                            Answer = 28f,
                            Difficulty = (byte)1,
                            Text = "14 + 14"
                        },
                        new
                        {
                            Id = new Guid("6ba8e87e-c9ed-458f-ac1d-40800197d764"),
                            Answer = 15f,
                            Difficulty = (byte)1,
                            Text = "15 + 0"
                        },
                        new
                        {
                            Id = new Guid("94d1dcb3-4ed8-4df1-aca7-870343b3427c"),
                            Answer = 16f,
                            Difficulty = (byte)1,
                            Text = "15 + 1"
                        },
                        new
                        {
                            Id = new Guid("04ea0cf2-551d-47c5-bf06-12396270bdb7"),
                            Answer = 17f,
                            Difficulty = (byte)1,
                            Text = "15 + 2"
                        },
                        new
                        {
                            Id = new Guid("021f7f23-b575-4237-a37b-6518173932d5"),
                            Answer = 18f,
                            Difficulty = (byte)1,
                            Text = "15 + 3"
                        },
                        new
                        {
                            Id = new Guid("cc254121-e2f8-4ffd-83bf-5b7178e684f1"),
                            Answer = 19f,
                            Difficulty = (byte)1,
                            Text = "15 + 4"
                        },
                        new
                        {
                            Id = new Guid("be4e21a1-02fa-48f5-8c12-ae4e0a5264a6"),
                            Answer = 20f,
                            Difficulty = (byte)1,
                            Text = "15 + 5"
                        },
                        new
                        {
                            Id = new Guid("5a5864f4-7ae0-4cc3-9fad-caa83ab16207"),
                            Answer = 21f,
                            Difficulty = (byte)1,
                            Text = "15 + 6"
                        },
                        new
                        {
                            Id = new Guid("433b6b14-2481-4976-9e69-9d9a591c8d50"),
                            Answer = 22f,
                            Difficulty = (byte)1,
                            Text = "15 + 7"
                        },
                        new
                        {
                            Id = new Guid("24d562bb-c89a-4d39-8bfc-1b4943de9b6d"),
                            Answer = 23f,
                            Difficulty = (byte)1,
                            Text = "15 + 8"
                        },
                        new
                        {
                            Id = new Guid("8f84ec6a-321e-4e2a-9722-c58091801a48"),
                            Answer = 24f,
                            Difficulty = (byte)1,
                            Text = "15 + 9"
                        },
                        new
                        {
                            Id = new Guid("efeb539d-e5d3-4fcb-a362-ca1440671a2a"),
                            Answer = 25f,
                            Difficulty = (byte)1,
                            Text = "15 + 10"
                        },
                        new
                        {
                            Id = new Guid("2f9a101e-25f4-4d65-959d-99c692930067"),
                            Answer = 26f,
                            Difficulty = (byte)1,
                            Text = "15 + 11"
                        },
                        new
                        {
                            Id = new Guid("796cfe00-9431-4f44-ab11-cadbfeb95a94"),
                            Answer = 27f,
                            Difficulty = (byte)1,
                            Text = "15 + 12"
                        },
                        new
                        {
                            Id = new Guid("1bf42073-ed27-4cbe-b676-c1ea547f2cde"),
                            Answer = 28f,
                            Difficulty = (byte)1,
                            Text = "15 + 13"
                        },
                        new
                        {
                            Id = new Guid("5ab79744-0786-432f-8ca6-7d0cbfb35421"),
                            Answer = 29f,
                            Difficulty = (byte)1,
                            Text = "15 + 14"
                        });
                });

            modelBuilder.Entity("JavaHateBE.model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe689ef8-8df3-4d33-94ca-f3b1a1fa23ad"),
                            Email = "david@example.com",
                            LastLogin = new DateTime(2024, 9, 29, 16, 45, 47, 559, DateTimeKind.Local).AddTicks(6300),
                            Password = "lky7elm96TArktWcrsc/BnahSZ8Rn2WMV5tYbjmSLLzyxuJYmxJEyTDp9UtHo0A8",
                            Username = "David"
                        },
                        new
                        {
                            Id = new Guid("b2b25912-86eb-439f-93ce-c6fb7171caa9"),
                            Email = "robbe@example.com",
                            LastLogin = new DateTime(2024, 9, 29, 16, 45, 47, 576, DateTimeKind.Local).AddTicks(460),
                            Password = "1A1qLT9m0ODKsyYkqWChw/OJlAucTQLhcvXGobw41vDwoXMt6jTOeGsPmKw9NYKt",
                            Username = "Robbe"
                        },
                        new
                        {
                            Id = new Guid("ef118dba-27b0-4113-9145-c1ed7da4fdc1"),
                            Email = "valdemar@example.com",
                            LastLogin = new DateTime(2024, 9, 29, 16, 45, 47, 592, DateTimeKind.Local).AddTicks(9810),
                            Password = "z3i6oB6C0WHzqQ42fwEhlZgcOKI0cJZr2G4P3kZyX2AV3e68Ktu6QMZQZo1Wxdry",
                            Username = "Valdemar"
                        },
                        new
                        {
                            Id = new Guid("1d352f3c-f683-4d8f-80fd-58e22274e450"),
                            Email = "matas@example.com",
                            LastLogin = new DateTime(2024, 9, 29, 16, 45, 47, 609, DateTimeKind.Local).AddTicks(6460),
                            Password = "7/tcPZ0ilHja0bm9c0d4cUTzJrqLv5exZxBuceBjQmB7RokvFDwSTMzpamSgnbPv",
                            Username = "Matas"
                        });
                });

            modelBuilder.Entity("JavaHateBE.model.Game", b =>
                {
                    b.HasOne("JavaHateBE.model.User", "Gamer")
                        .WithMany("Games")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gamer");
                });

            modelBuilder.Entity("JavaHateBE.model.Question", b =>
                {
                    b.HasOne("JavaHateBE.model.Game", null)
                        .WithMany("Questions")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("JavaHateBE.model.Game", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("JavaHateBE.model.User", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
